spring:
  application:
    name: hsf-provider
    
  hsf:
    version: 1.0.0
    timeout: 1000
    
  jpa:
    hibernate:
      ddl-auto: none
      
    database-platform: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/microfan
    username: microfan
    password: microfan

logging:
  level:
    root: INFO

    org:
      springframework:
        security: DEBUG

server:
  port: 18081

redis:
  server: localhost
  port: 6379
  password: microfan
  


mqtt:
  deviceInstance:
    server: localhost
    port: 1883
    user: microfan
    password: microfan

  middlewareInstance:
    server: localhost
    port: 1884
    user: microfan
    password: microfan
    
argos:
  announce:
    pingMilliseconds: 1800000
    

  cache:
    pingMilliseconds: 1800000
  subscribe:
    pingMilliseconds: 60000


